#!/usr/bin/env bash

# Clear previous build output files
echo "
Clear previous build output files..."
rm -rf dist .eslintcache .rollup.cache .lint.run.json .test.run.json && \

# Lint source files
# echo "
# Lint source files..."
# npx eslint --cache 'src/**' && \

# Compile code for server
echo "
Compile code ..." && \
npx tsc --outDir ./dist && \

# Test build
echo "
Test build" && \
npx mocha -r source-map-support/register dist/test/*.test.js
